development:
 adapter: postgresql
 encoding: unicode
 database: project1_dev
 pool: 5
 username: shobhit
 password:
 host: localhost

test:
 adapter: postgresql
 encoding: unicode
 database: project1_test
 pool: 5
 username: shobhit
 password:
 host: localhost